export const SET_REVIEW_DATA = "SET_REVIEW_DATA";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_NUMBER_IN_CART = "INCREMENT_NUMBER_IN_CART";
export const DECREMENT_NUMBER_FROM_CART = "DECREMENT_NUMBER_FROM_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const CHANGE_SHIPPING_COST = "CHANGE_SHIPPING_COST";
